# Generated by Django 3.1.6 on 2021-04-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20210412_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
