# Generated by Django 3.1.6 on 2021-04-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20210412_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
