# Generated by Django 3.1.6 on 2021-04-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_profile_image_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=''),
        ),
    ]
