# Generated by Django 3.1.6 on 2021-05-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20210428_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='staticfiles/assets/images/profiles/'),
        ),
    ]
