# Generated by Django 3.1.6 on 2021-06-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_profile_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='description',
        ),
    ]
