# Generated by Django 3.1.6 on 2021-02-19 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test', '0001_initial'),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='profile.profile')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='test.test')),
            ],
            options={
                'ordering': ['-created_at', 'updated_at'],
                'abstract': False,
            },
        ),
    ]
