# Generated by Django 3.1.6 on 2021-04-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultat', '0002_auto_20210221_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='creatifDesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultat',
            name='entreprenantDesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultat',
            name='investigateurDesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultat',
            name='methodiqueDesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultat',
            name='pratiqueDesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultat',
            name='socialDesc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
