# Generated by Django 3.1.6 on 2021-04-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultat', '0005_auto_20210412_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultat',
            name='image',
        ),
        migrations.AddField(
            model_name='resultat',
            name='imagePdf',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/assets/images/results/'),
        ),
    ]
