# Generated by Django 3.1.6 on 2021-05-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultat', '0006_auto_20210412_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultat',
            name='imagePdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
