# Generated by Django 3.1.6 on 2021-05-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultat', '0009_auto_20210509_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultat',
            name='imagePdf',
            field=models.FileField(blank=True, null=True, upload_to='staticfiles/assets/images/profiles/results'),
        ),
    ]
