# Generated by Django 3.1.6 on 2021-05-16 18:08

from django.db import migrations, models
import resultat.filesettings


class Migration(migrations.Migration):

    dependencies = [
        ('resultat', '0011_auto_20210516_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultat',
            name='imagePdf',
            field=models.FileField(blank=True, null=True, storage=resultat.filesettings.MyFileStorage(), upload_to='staticfiles/assets/images/results/'),
        ),
    ]
