# Generated by Django 3.1.6 on 2021-04-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210331_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullName',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
