# Generated by Django 3.1.6 on 2021-04-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20210408_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
