# Generated by Django 3.1.6 on 2021-02-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Questions',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='element',
            name='columns',
            field=models.ManyToManyField(blank=True, null=True, related_name='elements', to='test.Question'),
        ),
    ]
