# Generated by Django 3.1.6 on 2021-02-19 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_auto_20210219_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_at',
        ),
    ]
