# Generated by Django 3.1.6 on 2021-03-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_auto_20210219_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultparam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'PResultats',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='test',
            name='description',
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(related_name='tests', to='test.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='params',
            field=models.ManyToManyField(related_name='questions', to='test.Resultparam'),
        ),
    ]
