# Generated by Django 3.1.6 on 2021-03-08 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0004_auto_20210308_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={},
        ),
        migrations.RemoveField(
            model_name='test',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='test',
            name='updated_at',
        ),
    ]
