# Generated by Django 3.1.6 on 2021-06-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0008_auto_20210401_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='rating',
            field=models.CharField(blank=True, choices=[('BLANK', 'Blank'), ('TBIEN', 'Tbien'), ('BIEN', 'Bien'), ('MEDIOCRE', 'Mediocre')], default='BLANK', max_length=265, null=True),
        ),
    ]
