# Generated by Django 3.1.6 on 2021-06-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0009_test_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='bien_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='mediocre_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='tbien_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
